version: '2'
services:
  postgresql-service:
    ports:
       - "5432:5432"
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: "postgres"
